# Build
# -------------------------------------

language: node_js
node_js:
    - "4"
    - "5"
    - "6"

# Deployment
# -------------------------------------

deploy:
    provider: npm
    on:
        tags: true
        node: "5.11"
    api_key:
        secure: "LkQI++BnCZgw4RLAHPZRJXrpz80G0u5D6z91ttbunMTgo55+uVAfAjLxhm6Xm98C9TKNpFYnBuqzDBWZIqDH2GHaPDpfqUfDB4jbneni+2HqBvHaKekKSjNPtXVEp+UZJDF+YhdUHOBY9hvW/NvVcga2suSWIfEzd4LMxN2b3uCpApTYRu6KYRWc4iNhlSpa4RrI1GsoSZMyG9PpfAXY63l8xP4Sb0puMh4SisRe761WbooPykbmTjsyoI+0a2aPlLWaTZJWUEj6Xz4Takp6ObFbDoSm0H/XYmEQ/jDJ7VkG5i+kSN/dLVfa0y4uNQYM/vGjkfykT/SmLe+SEvPjCwRXr57LP+eLzFRMWrGPIrgbKPIoIC7O1ACrWsLIJ/zHBqwGnBS17bKJn9+zZ4DMOm+6ZjVFPddMMFGNYy1D9V1Ksq2kXZCfSMU61OofrmpfBTbUKALtVQ9XFGneOMbrMIy/zuBsVMpRqWvwpij2JQpzry/91Ur6IcKGLlg20ccdNaX28JC2PNAFGxcdVDEcJC95ho3PkN1a0slEM2cQWk1abRbDYDruMLl62J7ALfZTFhK8lMDqZIMi7oqRUcnYCAqupDdpoIzf0FAqcANk26xPeTQpa2OWIUvctxeH4IKaA+yOue6AWlJJw9igaoqRuWlWYlLNNz1RjX2KnRHiEP4="
    email: "lsphillips.mail@gmail.com"
